// Multi-entity VHDL example
// This demonstrates vhd2vl's support for files containing multiple entities
// Useful for files generated by tools like FloPoCo
// First entity: Simple register
// no timescale needed

module simple_reg(
input wire clk,
input wire rst,
input wire [7:0] d,
output reg [7:0] q
);





  always @(posedge clk, posedge rst) begin
    if(rst == 1'b1) begin
      q <= {8{1'b0}};
    end else begin
      q <= d;
    end
  end


endmodule
// Second entity: Simple adder

module simple_adder(
input wire [7:0] a,
input wire [7:0] b,
output wire [8:0] sum
);





  assign sum = (a) + (b);

endmodule
